2.4.0
rdkcentral/Lightning pull request #310
Opened 2021-07-01 19:45 UTC by erikhaandrikman

2021-07-01 19:54 UTC, g-zachar commented
I guess #302 should be reviewed before release since current pointer support is not complete.

2021-07-01 20:00 UTC, erikhaandrikman commented
Yes, will review this PR before the new release

2021-07-05 08:33 UTC, g-zachar requested changes
We should update dependencies to resolve #296 and #301

2021-07-06 13:41 UTC, g-zachar approved these changes

2021-07-06 14:12 UTC, merged