BD-1028: Compliance Issues in Lightning gh-pages repo
rdkcentral/Lightning pull request #315
Opened 2021-07-20 13:18 UTC by mallikarjuna54

2021-07-28 15:10 UTC, mhughesacn reviewed
Hi Mallikarjuna - a few comments here, but please see the BD ticket.

LICENSE as below.

README - please revert this change.

lightning-inspect.js - please revert; this looks like a typo.

2021-07-28 15:10 UTC, mhughesacn commented on LICENSE
> +
Please revert this change and append a copy of the MIT license.

2021-08-03 12:01 UTC, mhughesacn requested changes

2021-08-03 12:01 UTC, mhughesacn commented on devtools/lightning-inspect.js
> +window.attachInspector = function({Element, ElementCore, Stage, Component, ElementTexturizer, Texture}) {
This must be reverted - not sure where it came from.

2021-08-23 20:06 UTC, pradeeptakdas commented
Hi @wouterlucas 
Could you please review and merge this PR?

2021-08-30 13:50 UTC, pradeeptakdas commented
Hi @wouterlucas , 
Can you please merge this change-set? or Please suggest if you have any review comments.

2021-10-31 10:44 UTC, merged