BD-1028:Compliance Issues in Lightning gh-pages repo
rdkcentral/Lightning pull request #317
Opened 2021-08-02 06:26 UTC by mallikarjuna54

2021-08-03 12:11 UTC, mhughesacn requested changes
Hi Mallikarjuna - Please leave the existing facebook copyrights alone.  I am looking for Metrological headers on files under js/lightning/src and no more.  Thanks.

2021-08-03 12:11 UTC, mhughesacn commented on css/prism.css
> -/**
Please leave this header alone.

2021-08-03 12:11 UTC, mhughesacn commented on js/codetabs.js
> -/**
Please leave alone.

2021-08-03 12:11 UTC, mhughesacn commented on js/codetabs.js
> - * Copyright (c) 2017-present, Facebook, Inc.
Please leave alone.

2021-08-03 12:11 UTC, mhughesacn commented on js/scrollSpy.js
> -/**
Please revert

2021-08-04 13:54 UTC, mhughesacn approved these changes

2021-08-04 14:11 UTC, mhughesacn commented
Thanks Mallikarjuna.  Metrological will have to approve.

2021-08-23 20:06 UTC, pradeeptakdas commented
Hi @wouterlucas 
Could you please merge this PR?

2021-10-31 10:40 UTC, merged